#server:
#  port: 8888
#spring:
#  application:
#    name: youyou-live-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.32.3:8848
#        namespace: ddddfd2a-ca0d-46a8-ba2e-f74927da2350
#    gateway:
#      discovery:
#        locator:
#          enabled: true #开启配置信息
#      routes: #路由
#        # 用户api代理
#        - id: user-api
#          uri: lb://youyou-api-server
#          predicates:
#            - Path=/user/**
#
## 解决包冲突问题
#  main:
#    web-application-type: reactive
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false         #是否使用telnet查看状态
#  registry:
#    address: nacos://192.168.32.3:8848?namespace=ddddfd2a-ca0d-46a8-ba2e-f74927da2350
#    id: nacos-registry
#  protocol:                   #协议
#    name: dubbo
#    port: -1
#
#
#youyou:
#  autho:
#    token: youyou
#  gateway: ##白名单过滤
#    white-url-list:
#      - /user/mobileLogin
#      - /user/sendSMS
#
